### ISSUE TITLE
Docker MySQL 설치 및 테이블 생성

### ISSUE THREAD

**Issue by NCookies** [NCookies/pass-batch#3]
docker를 사용하여 MySQL을 설치하고 관련 설정 파일들을 작성한다.

## TODO

- [x] Docker Desktop 설치
- [x] 설정 파일 작성
- [x] Docker MySQL 설치
- [x] sql 작성 및 실행
